#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanTimeDirectories
\rm -f .setSet constant/cellDecomposition constant/cellDecomposition.gz
\rm -rf VTK
\rm -rf constant/polyMesh/sets
\cp -r sets constant/polyMesh/sets
\rm -rf 0
cp -r save 0
