#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="interOversetFoam"

\rm -rf 0
cp -r save 0
runApplication regionCellSets
runApplication setsToZones
runApplication setSet -batch setBatch.batch
( cd constant/polyMesh/sets/ ; \rm -f cellRegion0 cellRegion0.gz cellRegion1 cellRegion1.gz backFringe_old backFringe_old.gz backHole_old backHole_old.gz )
runApplication setFields

#runApplication $application

runApplication decomposePar -cellDist
runApplication decomposeSets -writeEmptySets
runParallel $application1 4
