#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanTimeDirectories
\rm -rf processor*
\rm -rf .setSet
\rm -rf 0/cellDist 0/cellDist.gz constant/cellDecomposition 
\rm -rf *.vtk
\rm -rf VTK
\rm -rf 0
\cp -r save 0
