#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application1="potentialOversetFoam"
application2="interOversetFoam"

\rm -rf 0
cp -r save 0
runApplication setsToZones
runApplication setSet -batch setBatch.batch
( cd constant/polyMesh/sets ; \rm -f backFringe_old backFringe_old.gz backHole_old backHole_old.gz )
runApplication setFields

#runApplication $application1 -writep
#runApplication $application2

runApplication decomposePar -cellDist
\rm -f constant/polyMesh/sets/background constant/polyMesh/sets/background.gz constant/polyMesh/sets/hull constant/polyMesh/sets/hull.gz
runApplication decomposeSets -writeEmptySets
runParallel $application1 4
runParallel $application2 4
