#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="interOversetFoam"

\rm -rf 0
cp -r save 0
runApplication setFields
runApplication potentialOversetFoam -writep

runApplication $application
