#!/bin/sh

( cd channelSimpleOverlapLaplace ; ./Allclean )
( cd channelSimpleOverlapLaplaceCutAlong ; ./Allclean )
( cd channelSimpleOverlapLaplaceCutAcross ; ./Allclean )

( cd channelSimpleOverlapPotentialScalarTransport ; ./Allclean )

( cd cylinderInSquareLaplace ; ./Allclean )
( cd cylinderInChannelPotentialScalarTransport ; ./Allclean )

( cd channelBodyFittedLaplace ; ./Allclean )
