#!/bin/sh

( cd channelSimpleOverlapLaplace ; ./Allrun )
( cd channelSimpleOverlapLaplaceCutAlong ; ./Allrun )
( cd channelSimpleOverlapLaplaceCutAcross ; ./Allrun )

( cd channelSimpleOverlapPotentialScalarTransport ; ./Allrun )

( cd cylinderInSquareLaplace ; ./Allrun )
( cd cylinderInChannelPotentialScalarTransport ; ./Allrun )

( cd channelBodyFittedLaplace ; ./Allrun )
