#!/bin/sh

( cd channelSimpleOverlapLaplace ; ./Allclean )
( cd channelSimpleOverlapPotentialScalarTransport ; ./Allclean )
( cd channelSimpleOverlapicoOversetFoam ; ./Allclean )

( cd cylinderInSquareLaplace ; ./Allclean )

( cd cylinderInChannelPotentialScalarTransport ; ./Allclean )
( cd cylinderInChannelicoOversetFoam ; ./Allclean )

( cd cylBumpinterOversetFoam ; ./Allclean )

( cd staticCylinderSheddingTest ; ./Allclean )
( cd navyCylinderSheddingTest ; ./Allclean )

( cd backStepLaminarBodyFitted ; ./Allclean )
#( cd backStepOversetLaminar ;  ./Allclean )

( cd suddenExpansionsimpleOversetFoam ; ./Allclean )

