#!/bin/sh

( cd channelSimpleOverlapLaplace ; ./Allrun )
( cd channelSimpleOverlapPotentialScalarTransport ; ./Allrun )
( cd channelSimpleOverlapicoOversetFoam ; ./Allrun )

( cd cylinderInSquareLaplace ; ./Allrun )

( cd cylinderInChannelPotentialScalarTransport ; ./Allrun )
( cd cylinderInChannelicoOversetFoam ; ./Allrun )


( cd cylBumpinterOversetFoam ; ./Allrun )

( cd staticCylinderSheddingTest ; ./Allrun )
( cd navyCylinderSheddingTest ; ./Allrun )

( cd backStepLaminarBodyFitted ; ./Allrun )
#( cd backStepOversetLaminar ;  ./Allrun )

( cd suddenExpansionsimpleOversetFoam ; ./Allrun )

( cd movingCylinderInChannelicoDyMOversetFoam ; ./Allrun )
