#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="laplacianFoam"

\cp -f blockMeshDict constant/polyMesh/blockMeshDict
runApplication blockMesh
\cp -f boundary constant/polyMesh/boundary
runApplication setSet -batch setBatch.batch
\rm -f constant/polyMesh/sets/*_old constant/polyMesh/sets/*_old.gz

#runApplication $application

runApplication decomposePar
runApplication decomposeSets
runParallel 2 $application

