#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

# Change defaultFaces patch to propellerHole
sed -i s/defaultFaces/propellerHole/g constant/polyMesh/boundary
sed -i s/empty/patch/g constant/polyMesh/boundary

runApplication checkMesh
