#!/bin/bash
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create propeller mesh
runApplication surfaceFeatureEdges propeller-full.stl geom.fms
runApplication cartesianMesh

runApplication checkMesh
