#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
#( cd backgroundMesh ; ./Allclean )
#( cd propellerMesh ; ./Allclean )
\rm -f .setSet constant/cellDecomposition constant/cellDecomposition.gz
\rm -rf constant/polyMesh/
mkdir constant/polyMesh
\rm -rf 0
cp -r save 0
\rm -rf fullForces hole* logPar
