#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="potentialDyMOversetFoam"

# Create background mesh
(cd backgroundMesh; ./Allrun)

# Copy propeller mesh here
\cp -rf propellerMesh/constant/polyMesh constant/

# Merge meshes and clean up
runApplication mergeMeshes .. propellerForDTC . backgroundMesh
\rm -rf constant/polyMesh
\mv 0.*/polyMesh constant
\rm -rf 0.*
\rm -f constant/polyMesh/pointZones constant/polyMesh/pointZones.gz constant/polyMesh/faceZones constant/polyMesh/faceZones.gz constant/polyMesh/cellZones constant/polyMesh/cellZones.gz

# Make cell zones for all regions and clean up
runApplication regionCellSets
runApplication setSet -batch setBatch.batch
\rm -f constant/polyMesh/sets/*_old constant/polyMesh/sets/*_old.gz
\rm -f constant/polyMesh/sets/cellRegion0 constant/polyMesh/sets/cellRegion0.gz constant/polyMesh/sets/cellRegion1 constant/polyMesh/sets/cellRegion1.gz
runApplication setsToZones

# Set up boundary patches
\cp -f boundary constant/polyMesh/boundary

# Check final mesh
runApplication checkMesh

## Run serial
#runApplication $application1
#runApplication $application2

runApplication decomposePar -cellDist
runApplication decomposeSets -writeEmptySets
runParallel $application 4
