#!/bin/sh
set -x

wmake oversetRegionID

wmake libso oversetMesh
wmake libso oversetDynamicFvMesh

wmake laplacianOversetFoam
wmake potentialOversetFoam
wmake scalarTransportOversetFoam
wmake icoOversetFoam
wmake simpleOversetFoam
wmake interOversetFoam

wmake icoDyMOversetFoam
