#!/bin/sh
set -x

wclean oversetRegionIndex

wclean oversetMesh
wclean oversetDynamicFvMesh

wclean laplacianOversetFoam
wclean potentialOversetFoam
wclean scalarTransportOversetFoam
wclean icoOversetFoam
wclean simpleOversetFoam
wclean interOversetFoam

wclean potentialDyMOversetFoam
wclean icoDyMOversetFoam
wclean pimpleDyMOversetFoam
