#!/bin/sh
set -x

wclean oversetRegionID

wclean oversetMesh
wclean oversetDynamicFvMesh

wclean laplacianOversetFoam
wclean potentialOversetFoam
wclean scalarTransportOversetFoam
wclean icoOversetFoam
wclean simpleOversetFoam
wclean interOversetFoam

wclean icoDyMOversetFoam
