#!/bin/sh
set -x

wclean oversetRegionID

wclean oversetMesh

wclean laplacianOversetFoam
wclean potentialOversetFoam
wclean scalarTransportOversetFoam
wclean icoOversetFoam
wclean simpleOversetFoam
wclean interOversetFoam

wclean icoDyMOversetFoam
