#!/bin/sh
set -x

wmake oversetRegionIndex

wmake libso oversetMesh
wmake libso oversetDynamicFvMesh

wmake laplacianOversetFoam
wmake potentialOversetFoam
wmake scalarTransportOversetFoam
wmake icoOversetFoam
wmake simpleOversetFoam
wmake interOversetFoam

wmake potentialDyMOversetFoam
wmake icoDyMOversetFoam
wmake pimpleDyMOversetFoam
