#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
( cd background ; cleanCase )
\rm -f .setSet
\rm -rf 0/cellDist 0/cellDist.gz constant/cellDecomposition 
\rm -rf *.vtk
\rm -rf constant/polyMesh-suboff
\rm -rf constant/polyMesh
mkdir constant/polyMesh
\rm -rf 0 holeTri*
cp -r save 0
