#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application1="potentialOversetFoam"
application2="simpleOversetFoam"

# Make background mesh
(cd background ; blockMesh )

# Convert inner suboff mesh from Fluent
gunzip suboff-boxer-oversetSmall.msh.gz
runApplication fluentMeshToFoam suboff-boxer-oversetSmall.msh
gzip suboff-boxer-oversetSmall.msh
cp -r constant/polyMesh constant/polyMesh-suboff

# Merge meshes and clean up
runApplication mergeMeshes .. suboffBoxerSmall . background
\rm -rf constant/polyMesh
\mv 1/polyMesh constant
rm -rf 1
\rm -f constant/polyMesh/pointZones constant/polyMesh/pointZones.gz constant/polyMesh/faceZones constant/polyMesh/faceZones.gz constant/polyMesh/cellZones constant/polyMesh/cellZones.gz

# Make cell zones for all regions and clean up
runApplication regionCellSets
runApplication setSet -batch setBatch.batch
\rm -f constant/polyMesh/sets/*_old constant/polyMesh/sets/*_old.gz
\rm -f constant/polyMesh/sets/cellRegion0 constant/polyMesh/sets/cellRegion0.gz constant/polyMesh/sets/cellRegion1 constant/polyMesh/sets/cellRegion1.gz
runApplication setsToZones

# Set up boundary patches
\cp -f boundary constant/polyMesh/boundary

# Run serial
#runApplication $application1
#runApplication $application2

#runApplication decomposePar -cellDist
#runApplication decomposeSets -writeEmptySets
#runParallel $application1 3
#runParallel $application2 3

